// ============================================================
// Reflexive TA Toolkit — interactivity
// ============================================================

(function () {
  'use strict';

  // ----- Theme toggle, back-to-top, scroll-reveal, nav-active -----
  const root = document.documentElement;
  const themeToggle = document.querySelector('.theme-toggle');
  const backToTop = document.querySelector('.back-to-top');
  const mediaQuery = window.matchMedia('(prefers-color-scheme: dark)');

  const getPreferredTheme = () => {
    const saved = localStorage.getItem('theme');
    return saved || (mediaQuery.matches ? 'dark' : 'light');
  };
  const setTheme = (theme) => {
    root.dataset.theme = theme;
    const isDark = theme === 'dark';
    themeToggle?.setAttribute('aria-pressed', String(isDark));
    themeToggle?.setAttribute('aria-label', `Switch to ${isDark ? 'light' : 'dark'} theme`);
  };
  setTheme(getPreferredTheme());
  root.classList.add('js');

  themeToggle?.addEventListener('click', () => {
    const next = root.dataset.theme === 'dark' ? 'light' : 'dark';
    localStorage.setItem('theme', next);
    setTheme(next);
  });
  mediaQuery.addEventListener('change', (e) => {
    if (!localStorage.getItem('theme')) setTheme(e.matches ? 'dark' : 'light');
  });

  document.querySelector('[data-current-year]').textContent = String(new Date().getFullYear());

  const updateBackToTop = () => backToTop?.classList.toggle('is-visible', window.scrollY > 600);
  window.addEventListener('scroll', updateBackToTop, { passive: true });
  updateBackToTop();
  backToTop?.addEventListener('click', () => window.scrollTo({ top: 0, behavior: 'smooth' }));

  const revealObserver = new IntersectionObserver((entries) => {
    entries.forEach((entry) => {
      if (entry.isIntersecting) {
        entry.target.classList.add('is-visible');
        revealObserver.unobserve(entry.target);
      }
    });
  }, { threshold: 0.1 });
  document.querySelectorAll('.reveal').forEach((el) => revealObserver.observe(el));

  const navLinks = [...document.querySelectorAll('.site-nav a')];
  const sections = navLinks
    .map((l) => document.querySelector(l.getAttribute('href')))
    .filter(Boolean);
  const sectionObserver = new IntersectionObserver((entries) => {
    entries.forEach((entry) => {
      if (!entry.isIntersecting) return;
      navLinks.forEach((l) => {
        const isCurrent = l.getAttribute('href') === `#${entry.target.id}`;
        l.classList.toggle('is-current', isCurrent);
        if (isCurrent) l.setAttribute('aria-current', 'location');
        else l.removeAttribute('aria-current');
      });
    });
  }, { rootMargin: '-35% 0px -55%', threshold: 0 });
  sections.forEach((s) => sectionObserver.observe(s));

  // ----- Data loading -----
  // Inline-first: content is embedded in index.html as
  // <script type="application/json" data-content="..."> blocks
  // (regenerated by tools/inline_content.py) so the page works from
  // file:// with a double-click. Fetch is the fallback when served.
  const fetchJSON = (path) => {
    const key = path.replace(/^content\//, '').replace(/\.json$/, '');
    const inline = document.querySelector(`script[data-content="${key}"]`);
    if (inline) return Promise.resolve(JSON.parse(inline.textContent));
    return fetch(path).then((r) => {
      if (!r.ok) throw new Error(`Fetch failed: ${path}`);
      return r.json();
    });
  };

  Promise.all([
    fetchJSON('content/pipeline-walkthrough.json'),
    fetchJSON('content/pipeline.json'),
    fetchJSON('content/decisions.json'),
    fetchJSON('content/reading-list.json'),
    fetchJSON('content/pressure-test.json'),
    fetchJSON('content/systems-comparison.json'),
    fetchJSON('content/runs/manifest.json'),
  ]).then(([flow, pipeline, decisions, reading, pressure, systems, runsManifest]) => {
    renderFlowWalkthrough(flow);
    renderArchitecture(pipeline);
    renderDecisions(decisions);
    renderReadingList(reading);
    renderPressureTest(pressure);
    renderSystemsComparison(systems);
    return fetchAllRuns(runsManifest);
  }).then((runs) => {
    renderDeepDives(runs);
  }).catch((err) => {
    console.error('Data load error:', err);
    const c = document.getElementById('deep-dives-content');
    if (c) c.innerHTML = `<p style="color:var(--warn);font-family:var(--font-mono);">Data load failed: ${err.message}. Open this page via a local server (e.g. <code>python3 -m http.server</code>), not via file://.</p>`;
  });

  // ----- Pipeline flow walkthrough (one paragraph, 7 stages) -----
  function renderFlowWalkthrough(data) {
    const root = document.getElementById('flow-walkthrough');
    if (!root) return;
    root.innerHTML = data.stages.map((s) => renderFlowCard(s)).join('');
  }

  function renderFlowCard(s) {
    const editClass = s.editable ? 'yes' : '';
    const editLabel = s.editable ? 'human' : 'auto';
    return `
      <article class="flow-card" data-stage="${s.num}">
        <span class="flow-card__editable ${editClass}">${editLabel}</span>
        <header class="flow-card__head">
          <span class="flow-card__num">${s.num}</span>
          <span class="flow-card__name">${escapeHTML(s.name)}</span>
        </header>
        <p class="flow-card__summary">${escapeHTML(s.summary)}</p>
        <div class="flow-card__data">${renderFlowData(s.data)}</div>
      </article>
    `;
  }

  function renderFlowData(d) {
    if (!d) return '';
    if (d.type === 'text') {
      return `
        <blockquote>${escapeHTML(d.text)}</blockquote>
        <span class="flow-card__meta">${escapeHTML(d.meta)}</span>
      `;
    }
    if (d.type === 'structure') {
      return `
        <span class="structure-label">${escapeHTML(d.label)}</span>
        <p class="gist">${escapeHTML(d.gist)}</p>
        <span class="flow-card__meta">${escapeHTML(d.meta)}</span>
      `;
    }
    if (d.type === 'excerpt') {
      return `
        <span class="excerpt-label">${escapeHTML(d.label)}</span>
        <blockquote>${escapeHTML(d.text)}</blockquote>
        <span class="flow-card__meta">${escapeHTML(d.meta)}</span>
      `;
    }
    if (d.type === 'codes') {
      const lines = d.codes.map((c) => `
        <div class="code-line">
          <span class="who">${escapeHTML(c.persona)}</span>
          <span class="label-text">
            <span class="badge ${c.type}">${c.type}</span>${escapeHTML(c.label)}
          </span>
        </div>
      `).join('');
      return `<div class="codes">${lines}</div>`;
    }
    if (d.type === 'verify') {
      return `
        <span class="verify-pass">${escapeHTML(d.result)}</span>
        <blockquote>${escapeHTML(d.quote)}</blockquote>
        <span class="flow-card__meta">${escapeHTML(d.meta)}</span>
      `;
    }
    if (d.type === 'merge') {
      return `
        <span class="merge-label">
          <span class="merge-action">${escapeHTML(d.action)}</span>${escapeHTML(d.label)}
        </span>
        <p class="merge-rationale">${escapeHTML(d.rationale)}</p>
      `;
    }
    if (d.type === 'theme') {
      return `
        <span class="theme-label">${escapeHTML(d.label)}</span>
        <p class="theme-statement">${escapeHTML(d.statement)}</p>
      `;
    }
    return '';
  }

  // ----- Architecture & scale -----
  function renderArchitecture(data) {
    const rail = document.getElementById('pipeline-rail');
    if (rail) {
      rail.innerHTML = `
        <p class="rail-intro">${escapeHTML(data.intro)}</p>
        <div class="rail">
          ${data.nodes.map((n) => `
            <div class="rail-node ${n.type === 'pause' ? 'is-pause' : ''}">
              <span class="flow-card__editable ${n.editable ? 'yes' : ''}">${n.editable ? 'human' : 'auto'}</span>
              <span class="rail-node__num">${escapeHTML(n.num)}</span>
              <span class="rail-node__name">${escapeHTML(n.name)}</span>
              <span class="rail-node__io"><strong>in</strong> ${escapeHTML(n.in)}</span>
              <span class="rail-node__io"><strong>out</strong> ${escapeHTML(n.out)}</span>
            </div>
          `).join('')}
        </div>
      `;
    }
    const ext = document.getElementById('extension-map');
    if (ext && data.extension_map) {
      ext.innerHTML = `
        <div class="compare-wrap">
          <table class="compare">
            <thead><tr><th>Trigger</th><th>Addition</th><th>Source</th></tr></thead>
            <tbody>
              ${data.extension_map.map((e) => `
                <tr><td>${escapeHTML(e.trigger)}</td><td>${escapeHTML(e.addition)}</td><td>${escapeHTML(e.source)}</td></tr>
              `).join('')}
            </tbody>
          </table>
        </div>
      `;
    }
    const scale = document.getElementById('scale-story');
    if (scale && data.scale_story) {
      scale.innerHTML = `
        <div class="compare-wrap">
          <table class="compare">
            <thead><tr><th>Stage</th><th>Corpus</th><th>Purpose</th><th>Source</th></tr></thead>
            <tbody>
              ${data.scale_story.map((s) => `
                <tr><td>${escapeHTML(s.stage)}</td><td>${escapeHTML(s.corpus)}</td><td>${escapeHTML(s.purpose)}</td><td>${escapeHTML(s.source)}</td></tr>
              `).join('')}
            </tbody>
          </table>
        </div>
      `;
    }
  }

  // ----- Locked decisions table -----
  const CATEGORY_LABELS = {
    'no-ml':       'Why no ML',
    'divergence':  'Why personas',
    'no-kappa':    'Why no κ',
    'file-based':  'Why files',
    'checkpoints': 'Why checkpoints',
    'structure':   'Why structure first',
  };

  function renderDecisions(data) {
    const filters = document.getElementById('decisions-filters');
    const list = document.getElementById('decisions-list');
    if (!filters || !list) return;

    // Filter chips
    const cats = ['all', ...new Set(data.decisions.map((d) => d.category))];
    filters.innerHTML = cats.map((c, i) => {
      const label = c === 'all' ? 'All' : (CATEGORY_LABELS[c] || c);
      return `<button type="button" data-filter="${c}" class="${i === 0 ? 'is-active' : ''}" aria-pressed="${i === 0}">${label}</button>`;
    }).join('');
    filters.querySelectorAll('button').forEach((btn) => {
      btn.addEventListener('click', () => {
        filters.querySelectorAll('button').forEach((b) => {
          b.classList.remove('is-active');
          b.setAttribute('aria-pressed', 'false');
        });
        btn.classList.add('is-active');
        btn.setAttribute('aria-pressed', 'true');
        const f = btn.dataset.filter;
        list.querySelectorAll('.decision').forEach((d) => {
          d.style.display = (f === 'all' || d.dataset.category === f) ? '' : 'none';
        });
      });
    });

    // Decision rows
    list.innerHTML = data.decisions.map((d) => `
      <details class="decision" data-category="${d.category}">
        <summary class="decision__head">
          <span class="decision__num">${d.num}</span>
          <span class="decision__cat">${CATEGORY_LABELS[d.category] || d.category}</span>
          <span class="decision__title">${escapeHTML(d.title)}</span>
          <span class="decision__chev" aria-hidden="true">›</span>
        </summary>
        <div class="decision__body">
          <div class="decision__tabs" role="tablist">
            <button type="button" data-tab="spec" class="is-active" role="tab" aria-selected="true">Spec</button>
            <button type="button" data-tab="research" role="tab" aria-selected="false" tabindex="-1">Research</button>
            <button type="button" data-tab="transcript" role="tab" aria-selected="false" tabindex="-1">Transcript</button>
            ${d.deviation ? '<button type="button" data-tab="deviation" role="tab" aria-selected="false" tabindex="-1">Literature disagrees</button>' : ''}
          </div>
          <div class="decision__panel is-active" data-panel="spec" role="tabpanel">
            <blockquote>${escapeHTML(d.spec)}</blockquote>
            <span class="citation">${escapeHTML(d.source || '')}</span>
          </div>
          <div class="decision__panel" data-panel="research" role="tabpanel">
            <blockquote>${escapeHTML(d.research)}</blockquote>
            <span class="citation">${escapeHTML(d.researchSource || 'research.md')}</span>
          </div>
          <div class="decision__panel" data-panel="transcript" role="tabpanel">
            <blockquote>${escapeHTML(d.transcript.quote)}</blockquote>
            <p><strong>From:</strong> ${escapeHTML(d.transcript.source)}</p>
            <p><strong>Why it matters:</strong> ${escapeHTML(d.transcript.why)}</p>
          </div>
          ${d.deviation ? `
          <div class="decision__panel" data-panel="deviation" role="tabpanel">
            <blockquote>${escapeHTML(d.deviation)}</blockquote>
            <span class="citation">deliberate deviation · revisit trigger in spec §9</span>
          </div>` : ''}
        </div>
      </details>
    `).join('');

    // Tab switching per row (click + arrow keys, aria-selected kept in sync)
    list.querySelectorAll('.decision').forEach((row) => {
      const tabs = [...row.querySelectorAll('.decision__tabs button')];
      const activate = (tabBtn) => {
        tabs.forEach((b) => {
          const active = b === tabBtn;
          b.classList.toggle('is-active', active);
          b.setAttribute('aria-selected', String(active));
          b.tabIndex = active ? 0 : -1;
        });
        row.querySelectorAll('.decision__panel').forEach((p) => p.classList.remove('is-active'));
        row.querySelector(`[data-panel="${tabBtn.dataset.tab}"]`).classList.add('is-active');
      };
      tabs.forEach((tabBtn, i) => {
        tabBtn.addEventListener('click', () => activate(tabBtn));
        tabBtn.addEventListener('keydown', (e) => {
          if (e.key !== 'ArrowRight' && e.key !== 'ArrowLeft') return;
          e.preventDefault();
          const next = tabs[(i + (e.key === 'ArrowRight' ? 1 : tabs.length - 1)) % tabs.length];
          activate(next);
          next.focus();
        });
      });
    });
  }

  // ----- Reading list -----
  function renderReadingList(data) {
    const root = document.getElementById('reading-list');
    if (!root) return;
    root.innerHTML = data.papers.map((p) => `
      <article class="paper">
        <h4>${escapeHTML(p.title)}</h4>
        <span class="paper-meta">${escapeHTML(p.authors)} · ${p.year} · ${escapeHTML(p.venue)}</span>
        <p>${escapeHTML(p.takeaway)}</p>
      </article>
    `).join('');
  }

  // ----- Pressure test -----
  function renderPressureTest(data) {
    const wrap = document.createElement('div');
    wrap.className = 'dive reveal';
    wrap.innerHTML = `
      <div class="dive__head">
        <div>
          <h3 class="dive__title">Pipeline pressure test</h3>
          <span class="dive__sub">12 nodes · click to expand</span>
        </div>
        <div class="dive__actions">
          <button class="button button--secondary" data-copy="pressure-test">Copy as markdown</button>
        </div>
      </div>
      <p style="margin-top:0;color:var(--muted);font-size:0.9rem;">${escapeHTML(data.intro)}</p>
      <div class="pt-grid">
        ${data.cards.map((c) => `
          <details class="pt-card" data-node="${c.id}">
            <summary>
              <span class="pt-num">${c.num}</span>
              <span class="pt-name">${escapeHTML(c.name)}</span>
              <span class="pt-chev" aria-hidden="true">›</span>
            </summary>
            <div class="pt-card__body">
              <div class="pt-card__row fail">
                <strong>Failure</strong>
                <p>${escapeHTML(c.failure)}</p>
              </div>
              <div class="pt-card__row audit">
                <strong>Audit catches</strong>
                <p>${escapeHTML(c.audit)}</p>
              </div>
              <div class="pt-card__row human">
                <strong>Human instead</strong>
                <p>${escapeHTML(c.human)}</p>
              </div>
            </div>
          </details>
        `).join('')}
      </div>
    `;
    const target = document.getElementById('deep-dives-content');
    if (target) target.appendChild(wrap);
    observeReveal(wrap);
    wireCopyButton(wrap, data, formatPressureTestMarkdown);
  }

  function formatPressureTestMarkdown(data) {
    const lines = [`# ${data.title}`, '', data.intro, ''];
    data.cards.forEach((c) => {
      lines.push(`## ${c.num}. ${c.name}`);
      lines.push(`**Failure.** ${c.failure}`);
      lines.push(`**Audit catches.** ${c.audit}`);
      lines.push(`**Human instead.** ${c.human}`);
      lines.push('');
    });
    return lines.join('\n');
  }

  // ----- Systems comparison -----
  function renderSystemsComparison(data) {
    const dimRows = data.dimensions.map((d) => {
      const us = data.systems.find((s) => s.id === 'us');
      const others = data.systems.filter((s) => s.id !== 'us');
      return `
        <tr>
          <td>${escapeHTML(d.label)}</td>
          <td class="us">${formatValue(us.values[d.id])}</td>
          ${others.map((s) => `<td>${formatValue(s.values[d.id])}</td>`).join('')}
        </tr>
      `;
    }).join('');

    const headerCells = data.systems.map((s) =>
      `<th class="${s.us ? 'us' : ''}">${escapeHTML(s.name)}</th>`
    ).join('');

    const wrap = document.createElement('div');
    wrap.className = 'dive reveal';
    wrap.innerHTML = `
      <div class="dive__head">
        <div>
          <h3 class="dive__title">Competing systems comparison</h3>
          <span class="dive__sub">6 systems × ${data.dimensions.length} dimensions</span>
        </div>
        <div class="dive__actions">
          <button class="button button--secondary" data-copy="systems">Copy as markdown</button>
        </div>
      </div>
      <div class="compare-wrap">
        <table class="compare">
          <thead>
            <tr>
              <th></th>
              ${headerCells}
            </tr>
          </thead>
          <tbody>${dimRows}</tbody>
        </table>
      </div>
    `;
    const target = document.getElementById('deep-dives-content');
    if (target) target.appendChild(wrap);
    observeReveal(wrap);
    wireCopyButton(wrap, data, formatSystemsMarkdown);
  }

  function formatValue(v) {
    if (v === 'yes') return '<span class="yes">✓ yes</span>';
    if (v === 'no')  return '<span class="no">— no</span>';
    if (v === 'partial') return '<span class="partial">~ partial</span>';
    return escapeHTML(v);
  }

  function formatSystemsMarkdown(data) {
    const head = ['| Dimension |', ...data.systems.map((s) => s.name + ' |')].join(' ');
    const sep  = ['|---|', ...data.systems.map(() => '---|')].join('');
    const rows = data.dimensions.map((d) => {
      const cells = data.systems.map((s) => s.values[d.id]).join(' | ');
      return `| ${d.label} | ${cells} |`;
    });
    return [`# Competing systems comparison`, '', head, sep, ...rows, ''].join('\n');
  }

  // ----- Worked examples -----
  function fetchAllRuns(manifest) {
    return Promise.all(manifest.runs.map((r) => fetchJSON(`content/runs/${r.file}`).then((d) => ({ ...d, ...r }))));
  }

  function renderDeepDives(runs) {
    const target = document.getElementById('deep-dives-content');
    if (!target || !runs.length) return;
    runs.forEach((run) => {
      const wrap = document.createElement('div');
      wrap.className = 'dive reveal';
      wrap.dataset.runId = run.id;
      wrap.innerHTML = `
        <div class="dive__head">
          <div>
            <h3 class="dive__title">${escapeHTML(run.title)}</h3>
            <span class="dive__sub">${escapeHTML(run.subtitle || '')} · ${run.steps.length} pipeline artifacts</span>
          </div>
          <div class="dive__actions">
            <button class="button button--secondary" data-copy="run">Copy as markdown</button>
          </div>
        </div>
        <div class="stepper">
          <div class="stepper__col">
            <h4>Transcript excerpt</h4>
            <div class="transcript" data-role="transcript"></div>
          </div>
          <div class="stepper__col">
            <h4>Pipeline output</h4>
            <div class="artifact" data-role="artifact"></div>
          </div>
        </div>
      `;
      target.appendChild(wrap);
      observeReveal(wrap);

      const tRoot = wrap.querySelector('[data-role="transcript"]');
      const aRoot = wrap.querySelector('[data-role="artifact"]');

      // Render transcript paragraphs
      tRoot.innerHTML = run.paragraphs.map((p) => `
        <p data-pid="${p.id}">
          <span class="speaker">${escapeHTML(p.speaker || '')}</span>${escapeHTML(p.text)}
        </p>
      `).join('');

      // Render artifact steps
      aRoot.innerHTML = run.steps.map((s, i) => renderArtifactStep(s, i)).join('');

      // Wire click-to-highlight
      const syncActive = (pid) => {
        tRoot.querySelectorAll('p').forEach((p) => p.classList.toggle('is-active', p.dataset.pid === pid));
        aRoot.querySelectorAll('.artifact-step').forEach((s) => {
          const ids = (run.steps[parseInt(s.dataset.idx, 10)] || {}).paragraph_ids || [];
          s.classList.toggle('is-active', ids.includes(pid));
        });
      };
      tRoot.querySelectorAll('p').forEach((p) => {
        p.addEventListener('click', () => syncActive(p.dataset.pid));
        p.addEventListener('mouseenter', () => syncActive(p.dataset.pid));
      });

      // Copy markdown
      wireCopyButton(wrap, run, () => formatRunMarkdown(run));
    });
  }

  function renderArtifactStep(step, idx) {
    let body = '';
    if (step.type === 'structure') {
      body = `
        <span class="meta">StructureDoc · section ${escapeHTML(step.content.section_id || '')}</span>
        <p><strong>${escapeHTML(step.content.gist)}</strong></p>
        <p style="color:var(--muted);font-family:var(--font-mono);font-size:0.78rem;">chars ${step.content.char_start}–${step.content.char_end}</p>
      `;
    } else if (step.type === 'code') {
      const tBadge = step.code_type === 'latent' ? '<span class="badge latent">latent</span>' : '<span class="badge semantic">semantic</span>';
      body = `
        <span class="meta">Persona ${escapeHTML(step.persona || '?')} · code</span>
        <h5>${tBadge}${escapeHTML(step.label)}</h5>
        <blockquote>“${escapeHTML(step.quote)}”</blockquote>
        <span class="rationale">${escapeHTML(step.rationale)}</span>
      `;
    } else if (step.type === 'merge') {
      body = `
        <span class="meta">Conciliator · merge decision</span>
        <h5><span class="badge merge">${escapeHTML(step.action || 'merge')}</span>${escapeHTML(step.label || '')}</h5>
        <p>${escapeHTML(step.note || '')}</p>
        ${step.rationale ? `<span class="rationale">${escapeHTML(step.rationale)}</span>` : ''}
      `;
    } else if (step.type === 'human') {
      body = `
        <span class="meta">Human · ${escapeHTML(step.decision || 'edit')}</span>
        <h5><span class="badge human">human</span>${escapeHTML(step.label || '')}</h5>
        <p>${escapeHTML(step.note || '')}</p>
        ${step.feed_forward ? `<span class="rationale">${escapeHTML(step.feed_forward)}</span>` : ''}
      `;
    } else if (step.type === 'memo') {
      body = `
        <span class="meta">Reconcile · drift memo (advisory, never blocks)</span>
        <h5><span class="badge memo">memo</span>${escapeHTML(step.label || '')}</h5>
        <p>${escapeHTML(step.note || '')}</p>
      `;
    } else if (step.type === 'theme') {
      body = `
        <span class="meta">Candidate theme</span>
        <h5>${escapeHTML(step.label)}</h5>
        <p>${escapeHTML(step.statement || '')}</p>
      `;
    }
    return `<div class="artifact-step" data-idx="${idx}">
      <span class="meta">${escapeHTML(step.title || '')}</span>
      ${body}
    </div>`;
  }

  function formatRunMarkdown(run) {
    const lines = [`# ${run.title}`, '', run.subtitle || '', ''];
    run.paragraphs.forEach((p) => {
      lines.push(`**${p.speaker || ''}:** ${p.text}`);
    });
    lines.push('', '---', '', '## Pipeline artifacts', '');
    run.steps.forEach((s) => {
      lines.push(`### ${s.title}`);
      if (s.type === 'structure') {
        lines.push(`- **Section ${s.content.section_id}** (chars ${s.content.char_start}–${s.content.char_end})`);
        lines.push(`- ${s.content.gist}`);
      } else if (s.type === 'code') {
        lines.push(`- **Persona ${s.persona} · ${s.code_type} code:** ${s.label}`);
        lines.push(`- Quote: “${s.quote}”`);
        lines.push(`- Rationale: ${s.rationale}`);
      } else if (s.type === 'merge') {
        lines.push(`- **Conciliator · ${s.action}:** ${s.label}`);
        lines.push(`- ${s.note || ''}`);
        if (s.rationale) lines.push(`- Rationale: ${s.rationale}`);
      } else if (s.type === 'human') {
        lines.push(`- **HumanDecision · ${s.decision || 'edit'}:** ${s.label}`);
        lines.push(`- ${s.note || ''}`);
        if (s.feed_forward) lines.push(`- Feed-forward: ${s.feed_forward}`);
      } else if (s.type === 'memo') {
        lines.push(`- **Drift memo (advisory):** ${s.label}`);
        lines.push(`- ${s.note || ''}`);
      } else if (s.type === 'theme') {
        lines.push(`- **Theme:** ${s.label}`);
      }
      lines.push('');
    });
    return lines.join('\n');
  }

  // ----- Copy-as-markdown -----
  function wireCopyButton(wrap, data, formatter) {
    const btn = wrap.querySelector('[data-copy]');
    if (!btn) return;
    btn.addEventListener('click', async () => {
      const text = formatter(data);
      try {
        await navigator.clipboard.writeText(text);
        const orig = btn.textContent;
        btn.textContent = 'Copied';
        setTimeout(() => { btn.textContent = orig; }, 1500);
      } catch (e) {
        console.error('Clipboard error:', e);
        btn.textContent = 'Copy failed';
      }
    });
  }

  // ----- Utils -----
  function escapeHTML(s) {
    return String(s == null ? '' : s)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#39;');
  }

  function observeReveal(el) {
    const obs = new IntersectionObserver((entries) => {
      entries.forEach((e) => {
        if (e.isIntersecting) {
          e.target.classList.add('is-visible');
          obs.unobserve(e.target);
        }
      });
    }, { threshold: 0.1 });
    obs.observe(el);
  }
})();
