#!/usr/bin/env python3
"""Regenerate the inline <script type="application/json"> blocks in
index.html from content/**/*.json, so the page works from file://
(double-click) without a local server. content/ stays the single
source of truth: edit a JSON, then re-run this script.

The blocks live between the CONTENT:BEGIN / CONTENT:END markers.
script.js reads inline blocks first and falls back to fetch().
"""
import json, glob, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INDEX = os.path.join(ROOT, 'index.html')
BEGIN = '<!-- CONTENT:BEGIN (generated by tools/inline_content.py — do not edit by hand) -->'
END = '<!-- CONTENT:END -->'

def build_blocks():
    blocks = []
    paths = sorted(glob.glob(os.path.join(ROOT, 'content', '**', '*.json'), recursive=True))
    for p in paths:
        key = os.path.relpath(p, os.path.join(ROOT, 'content')).removesuffix('.json')
        with open(p, encoding='utf-8') as fh:
            data = json.load(fh)  # validates JSON as a side effect
        payload = json.dumps(data, ensure_ascii=False)
        # JSON inside <script> may not contain "</script"; escape the slash.
        payload = payload.replace('</', '<\\/')
        blocks.append(f'<script type="application/json" data-content="{key}">{payload}</script>')
    return '\n'.join(blocks)

def main():
    with open(INDEX, encoding='utf-8') as fh:
        html = fh.read()
    section = f'{BEGIN}\n{build_blocks()}\n{END}'
    if BEGIN in html:
        html = re.sub(re.escape(BEGIN) + r'.*?' + re.escape(END), lambda _: section, html, flags=re.S)
    else:
        html = html.replace('<script src="script.js"></script>',
                            f'{section}\n<script src="script.js"></script>')
    with open(INDEX, 'w', encoding='utf-8') as fh:
        fh.write(html)
    n = section.count('data-content=')
    print(f'Inlined {n} content files into index.html')

if __name__ == '__main__':
    main()
